### ISSUE TITLE
Can't break candianite ore

### ISSUE THREAD

**Issue by fernandito1** [Skizzik-Industries/Project-Apple#3]
**Describe the bug**
I can't break candianite ore 
**To Reproduce**
1. When I try to break candianite ore with any tool it will take really long and won't drop anything
2. The only way after like 10m looking for a way to mine it was with tnt

**Expected behavior**
It should drop even with a wooden pick

**Screenshots**

**Please complete the following information:**
- B3.2-2.0.0
- 1.17.1
- Crash Log [via Gist, Pastebin or any other]

**Additional context**
I was told to do this in the discord

**Comment by uSkizzik** [comment]
So, the issue seems to be fixed in the fifth beta and I haven't touched anything. 
Though the ore requires a stone pick, similarly to the vanilla iron ore since it's mainly just a rip-off.
I recommend ignoring this issue since candianite isn't very useful (heck it's the same as iron) and waiting for the fifth beta unless you want the Spooktober update and you aren't playing on a server. (Latest available beta kicks players from the server when rendering the Skizzik)
